//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.innsys.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "fillPdfAndStore", namespace = "http://innsys.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fillPdfAndStore", namespace = "http://innsys.com/", propOrder = {
    "documentId",
    "inputValues"
})
public class FillPdfAndStore {

    @XmlElement(name = "documentId", namespace = "")
    private String documentId;
    @XmlElement(name = "inputValues", namespace = "", nillable = true)
    private com.innsys.KeyValuePair[] inputValues;

    /**
     * 
     * @return
     *     returns String
     */
    public String getDocumentId() {
        return this.documentId;
    }

    /**
     * 
     * @param documentId
     *     the value for the documentId property
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    /**
     * 
     * @return
     *     returns KeyValuePair[]
     */
    public com.innsys.KeyValuePair[] getInputValues() {
        return this.inputValues;
    }

    /**
     * 
     * @param inputValues
     *     the value for the inputValues property
     */
    public void setInputValues(com.innsys.KeyValuePair[] inputValues) {
        this.inputValues = inputValues;
    }

}
